[package]
name = "stella-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
clap.workspace = true
image = { workspace = true, features = ["webp"] }
pollster.workspace = true
rodio = { workspace = true, features = ["playback"] }
stella-assets = { path = "../stella-assets" }
stella-script = { path = "../stella-script" }
skrifa.workspace = true
tiny-skia.workspace = true
wgpu.workspace = true
winit.workspace = true
