[package]
name = "stella-script"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aes.workspace = true
base64.workspace = true
cbc.workspace = true
clap.workspace = true
fontdb.workspace = true
getrandom.workspace = true
libc.workspace = true
harfrust.workspace = true
skrifa.workspace = true
unicode-bidi.workspace = true
unicode-script.workspace = true
unicode-segmentation.workspace = true
ureq.workspace = true
clipper2-rust.workspace = true
mlua.workspace = true
lzma-rust2.workspace = true
rodio.workspace = true
serde.workspace = true
serde_json.workspace = true
plist.workspace = true
quick-xml.workspace = true
time.workspace = true
smallvec.workspace = true
stella-assets = { path = "../stella-assets" }
thiserror.workspace = true
