[package]
name = "stella-script"
version.workspace = true
edition.workspace = true
license = "(AGPL-3.0-or-later) AND BSL-1.0"
rust-version.workspace = true

[dependencies]
aes.workspace = true
cbc.workspace = true
clap.workspace = true
fontdb.workspace = true
ttf-parser.workspace = true
rustybuzz.workspace = true
unicode-bidi.workspace = true
unicode-script.workspace = true
unicode-segmentation.workspace = true
ureq.workspace = true
clipper2-rust.workspace = true
mlua.workspace = true
rodio.workspace = true
serde_json.workspace = true
smallvec.workspace = true
stella-assets = { path = "../stella-assets" }
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
